# Generated by Django 3.2.25 on 2025-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='model_thumbnails/')),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '3d_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
