# Generated by Django 5.2.16 on 2026-07-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_role_profiles(apps, schema_editor):
    SchoolMembership = apps.get_model("lab", "SchoolMembership")
    LearnerProfile = apps.get_model("lab", "LearnerProfile")
    InstructorProfile = apps.get_model("lab", "InstructorProfile")
    learner_ids = SchoolMembership.objects.filter(role="learner", is_active=True).values_list(
        "user_id", flat=True
    )
    instructor_ids = SchoolMembership.objects.filter(
        role="instructor", is_active=True
    ).values_list("user_id", flat=True)
    LearnerProfile.objects.bulk_create(
        [LearnerProfile(user_id=user_id) for user_id in set(learner_ids)],
        ignore_conflicts=True,
    )
    InstructorProfile.objects.bulk_create(
        [InstructorProfile(user_id=user_id) for user_id in set(instructor_ids)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0007_schoolinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="lab.school",
                    ),
                ),
            ],
            options={"ordering": ["-academic_year", "name"]},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="lab.cohort",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["cohort__name", "learner__username"]},
        ),
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(blank=True, max_length=60)),
                ("qualifications", models.JSONField(blank=True, default=list)),
                ("biography", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=60)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("rw", "Kinyarwanda")],
                        default="en",
                        max_length=8,
                    ),
                ),
                (
                    "accessibility_notes",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Learning accommodations only; do not store diagnoses or unrelated "
                            "medical data."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="lab.course",
                    ),
                ),
            ],
            options={"ordering": ["course__title", "order"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="lab.module",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="lab.school",
                    ),
                ),
            ],
            options={"ordering": ["school__name", "name"]},
        ),
        migrations.AddField(
            model_name="cohort",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohorts",
                to="lab.program",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="lab.program",
            ),
        ),
        migrations.RunPython(migrate_role_profiles, migrations.RunPython.noop),
        migrations.DeleteModel(name="UserProfile"),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("cohort", "learner"),
                name="unique_cohort_learner_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "code"), name="unique_course_module_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_course_module_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="unique_school_program_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="unique_school_cohort_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starts_on__isnull", True),
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="cohort_end_not_before_start",
            ),
        ),
    ]
