# Generated by Django 5.2.16 on 2026-07-17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_lesson_workflow_timestamps(apps, schema_editor):
    Lesson = apps.get_model("lab", "Lesson")
    Lesson.objects.filter(status__in=["review", "published", "retired"]).update(
        submitted_at=F("created_at")
    )
    Lesson.objects.filter(status__in=["published", "retired"]).update(
        reviewed_at=F("updated_at"),
        published_at=F("updated_at"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0008_curriculum_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="curriculum_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="competency",
            name="evidence_rules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="competency",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
        migrations.AddField(
            model_name="competency",
            name="mastery_criteria",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lesson",
            name="authored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_version",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("rw", "Kinyarwanda"),
                    ("en-rw", "English and Kinyarwanda"),
                ],
                default="en",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocks_lessons",
                symmetrical=False,
                to="lab.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "In review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("retired", "Retired"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            backfill_lesson_workflow_timestamps,
            migrations.RunPython.noop,
        ),
    ]
