# Generated by Django 5.2.16 on 2026-07-20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_versioned_simulations(apps, schema_editor):
    GradingPolicy = apps.get_model("lab", "GradingPolicy")
    SimulationScenario = apps.get_model("lab", "SimulationScenario")
    Lesson = apps.get_model("lab", "Lesson")
    ProcedureStep = apps.get_model("lab", "ProcedureStep")
    Assignment = apps.get_model("lab", "Assignment")
    Attempt = apps.get_model("lab", "Attempt")

    now = timezone.now()
    policy, _ = GradingPolicy.objects.get_or_create(
        code="standard-deterministic",
        version=1,
        defaults={
            "name": "Standard deterministic practical assessment",
            "algorithm": "base-minus-event-penalties-v1",
            "base_score": 100,
            "incorrect_action_penalty": 5,
            "safety_critical_penalty": 15,
            "requires_review_on_safety_error": False,
            "rules": {
                "algorithm": "base-minus-event-penalties",
                "minimumScore": 0,
            },
            "status": "published",
            "published_at": now,
        },
    )

    scenarios = {}
    for lesson in Lesson.objects.all().iterator():
        steps = list(
            ProcedureStep.objects.filter(lesson_id=lesson.pk)
            .order_by("order")
            .values(
                "id",
                "order",
                "code",
                "title",
                "instruction",
                "action_code",
                "feedback",
                "safety_critical",
                "points",
                "metadata",
            )
        )
        scenario_status = (
            "published" if lesson.status == "published" and steps else "draft"
        )
        scenario, _ = SimulationScenario.objects.get_or_create(
            lesson_id=lesson.pk,
            version=lesson.content_version,
            defaults={
                "title": f"{lesson.title} — scenario",
                "definition": {"format": "opedu-scenario/v1", "steps": steps},
                "grading_policy_id": policy.pk,
                "status": scenario_status,
                "published_at": lesson.published_at if scenario_status == "published" else None,
            },
        )
        scenarios[lesson.pk] = scenario

    for assignment in Assignment.objects.all().iterator():
        scenario = scenarios[assignment.lesson_id]
        Assignment.objects.filter(pk=assignment.pk).update(scenario_id=scenario.pk)

    for attempt in Attempt.objects.select_related("assignment").all().iterator():
        scenario = scenarios[attempt.assignment.lesson_id]
        Attempt.objects.filter(pk=attempt.pk).update(
            scenario_id=scenario.pk,
            grading_policy_id=scenario.grading_policy_id,
        )


class Migration(migrations.Migration):
    dependencies = [("lab", "0009_lesson_governance")]

    operations = [
        migrations.CreateModel(
            name="GradingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                (
                    "version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "algorithm",
                    models.CharField(
                        default="base-minus-event-penalties-v1",
                        max_length=60,
                    ),
                ),
                (
                    "base_score",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "incorrect_action_penalty",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "safety_critical_penalty",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("requires_review_on_safety_error", models.BooleanField(default=False)),
                ("rules", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["code", "-version"]},
        ),
        migrations.CreateModel(
            name="AssetPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                (
                    "version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                (
                    "sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$",
                                "Enter a lowercase SHA-256 digest.",
                            )
                        ],
                    ),
                ),
                ("total_byte_size", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_packages",
                        to="lab.course",
                    ),
                ),
            ],
            options={"ordering": ["course__title", "code", "-version"]},
        ),
        migrations.CreateModel(
            name="AssetFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("mime_type", models.CharField(max_length=120)),
                ("byte_size", models.PositiveBigIntegerField()),
                (
                    "sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$",
                                "Enter a lowercase SHA-256 digest.",
                            )
                        ],
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="lab.assetpackage",
                    ),
                ),
            ],
            options={"ordering": ["path"]},
        ),
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("definition", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenarios",
                        to="lab.assetpackage",
                    ),
                ),
                (
                    "grading_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenarios",
                        to="lab.gradingpolicy",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenarios",
                        to="lab.lesson",
                    ),
                ),
            ],
            options={"ordering": ["lesson__title", "-version"]},
        ),
        migrations.AddConstraint(
            model_name="gradingpolicy",
            constraint=models.UniqueConstraint(
                fields=("code", "version"),
                name="unique_grading_policy_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetpackage",
            constraint=models.UniqueConstraint(
                fields=("course", "code", "version"),
                name="unique_course_asset_package_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetfile",
            constraint=models.UniqueConstraint(
                fields=("package", "path"),
                name="unique_asset_file_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationscenario",
            constraint=models.UniqueConstraint(
                fields=("lesson", "version"),
                name="unique_lesson_scenario_version",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="scenario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="lab.simulationscenario",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="grading_policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="lab.gradingpolicy",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="scenario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="lab.simulationscenario",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="assignment",
            name="unique_lesson_learner_assignment",
        ),
        migrations.RunPython(backfill_versioned_simulations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="assignment",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="lab.simulationscenario",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="grading_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="lab.gradingpolicy",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="lab.simulationscenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("scenario", "learner"),
                name="unique_scenario_learner_assignment",
            ),
        ),
    ]
