# Generated by Django 5.2.16 on 2026-07-20

from collections import defaultdict
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def normalize_steps_and_backfill_results(apps, schema_editor):
    ProcedureStep = apps.get_model("lab", "ProcedureStep")
    AcceptableAction = apps.get_model("lab", "AcceptableAction")
    StepFeedback = apps.get_model("lab", "StepFeedback")
    SimulationScenario = apps.get_model("lab", "SimulationScenario")
    Attempt = apps.get_model("lab", "Attempt")
    StepResult = apps.get_model("lab", "StepResult")
    CompetencyResult = apps.get_model("lab", "CompetencyResult")
    Competency = apps.get_model("lab", "Competency")

    for step in ProcedureStep.objects.select_related("lesson").all().iterator():
        AcceptableAction.objects.get_or_create(
            step_id=step.pk,
            action_code=step.action_code,
            defaults={"label": step.title, "is_primary": True},
        )
        StepFeedback.objects.get_or_create(
            step_id=step.pk,
            outcome="correct",
            defaults={"message": step.feedback},
        )
        step.competencies.add(*step.lesson.competencies.values_list("pk", flat=True))

    for scenario in SimulationScenario.objects.select_related("lesson").all().iterator():
        definition = dict(scenario.definition)
        definition["format"] = "opedu-scenario/v2"
        competencies = list(
            scenario.lesson.competencies.order_by("code").values(
                "id",
                "code",
                "title",
                "mastery_threshold",
            )
        )
        definition["competencies"] = competencies
        step_by_code = {
            step.code: step
            for step in ProcedureStep.objects.filter(lesson_id=scenario.lesson_id).prefetch_related(
                "acceptable_actions",
                "feedback_rules",
                "competencies",
            )
        }
        enriched_steps = []
        for snapshot in definition.get("steps", []):
            snapshot = dict(snapshot)
            step = step_by_code.get(snapshot.get("code"))
            if step is not None:
                snapshot["acceptable_actions"] = [
                    {
                        "action_code": action.action_code,
                        "label": action.label,
                        "is_primary": action.is_primary,
                        "tolerance": None,
                    }
                    for action in step.acceptable_actions.all()
                ]
                snapshot["feedback_rules"] = {
                    feedback.outcome: feedback.message for feedback in step.feedback_rules.all()
                }
                snapshot["competency_codes"] = list(
                    step.competencies.order_by("code").values_list("code", flat=True)
                )
            snapshot.setdefault("acceptable_actions", [])
            snapshot.setdefault("feedback_rules", {"correct": snapshot.get("feedback", "")})
            snapshot.setdefault("competency_codes", [item["code"] for item in competencies])
            snapshot.setdefault("hints", [])
            snapshot.setdefault("tolerances", [])
            snapshot.setdefault("tools", [])
            snapshot.setdefault("hazards", [])
            enriched_steps.append(snapshot)
        definition["steps"] = enriched_steps
        SimulationScenario.objects.filter(pk=scenario.pk).update(definition=definition)

    for attempt in Attempt.objects.select_related(
        "scenario",
        "grading_policy",
        "assignment__lesson__course",
    ).filter(status__in=["completed", "requires_review"]):
        _backfill_attempt_results(
            attempt,
            StepResult,
            CompetencyResult,
            Competency,
        )


def _backfill_attempt_results(attempt, StepResult, CompetencyResult, Competency):
    steps = attempt.scenario.definition.get("steps", [])
    events = list(attempt.events.order_by("sequence"))
    events_by_step = defaultdict(list)
    for event in events:
        step_code = event.payload.get("stepCode") or event.payload.get("expectedStepCode")
        if step_code:
            events_by_step[step_code].append(event)

    step_results = {}
    for step in steps:
        step_events = events_by_step[step["code"]]
        incorrect = [
            event
            for event in step_events
            if event.event_type in {"incorrect_action", "tolerance_failed"}
        ]
        hints = [event for event in step_events if event.event_type == "hint_used"]
        completions = [event for event in step_events if event.event_type == "step_completed"]
        safety_violations = sum(
            event.payload.get("safetyCritical") is True for event in incorrect
        )
        available = Decimal(step.get("points", 10))
        penalties = sum(
            (
                attempt.grading_policy.safety_critical_penalty
                if event.payload.get("safetyCritical") is True
                else attempt.grading_policy.incorrect_action_penalty
            )
            for event in incorrect
        ) + sum(int(event.payload.get("pointsPenalty", 0)) for event in hints)
        achieved = max(Decimal(0), available - Decimal(penalties))
        started_at = step_events[0].occurred_at if step_events else attempt.started_at
        completed_at = (
            completions[-1].occurred_at
            if completions
            else attempt.completed_at or attempt.updated_at
        )
        result, _ = StepResult.objects.get_or_create(
            attempt_id=attempt.pk,
            step_code=step["code"],
            defaults={
                "outcome": "requires_review"
                if safety_violations and attempt.grading_policy.requires_review_on_safety_error
                else "passed"
                if completions
                else "failed",
                "attempts_count": len(incorrect) + len(completions),
                "hints_used": len(hints),
                "duration_seconds": max(0, int((completed_at - started_at).total_seconds())),
                "achieved_points": achieved,
                "available_points": available,
                "tolerance_passed": None,
                "safety_violations": safety_violations,
                "evidence_sequences": [event.sequence for event in step_events],
                "completed_at": completed_at,
            },
        )
        step_results[step["code"]] = result

    snapshots = attempt.scenario.definition.get("competencies", [])
    competency_by_code = {
        item.code: item
        for item in Competency.objects.filter(
            course_id=attempt.assignment.lesson.course_id,
            code__in=[snapshot["code"] for snapshot in snapshots],
        )
    }
    states = []
    all_codes = {snapshot["code"] for snapshot in snapshots}
    for snapshot in snapshots:
        competency = competency_by_code.get(snapshot["code"])
        if competency is None:
            continue
        relevant = [
            step_results[step["code"]]
            for step in steps
            if snapshot["code"] in (step.get("competency_codes") or all_codes)
        ]
        available = sum((result.available_points for result in relevant), Decimal(0))
        achieved = sum((result.achieved_points for result in relevant), Decimal(0))
        percentage = (
            (achieved / available * Decimal(100)).quantize(Decimal("0.01"))
            if available
            else Decimal(0)
        )
        threshold = int(snapshot.get("mastery_threshold", competency.mastery_threshold))
        state = (
            "requires_review"
            if any(result.outcome == "requires_review" for result in relevant)
            else "mastered"
            if percentage >= threshold
            else "developing"
            if available
            else "not_demonstrated"
        )
        result, _ = CompetencyResult.objects.get_or_create(
            attempt_id=attempt.pk,
            competency_id=competency.pk,
            defaults={
                "competency_code": competency.code,
                "achieved_points": achieved,
                "available_points": available,
                "mastery_percentage": percentage,
                "mastery_threshold": threshold,
                "mastery_state": state,
                "evidence": [
                    {
                        "stepCode": item.step_code,
                        "stepResultId": item.pk,
                        "eventSequences": item.evidence_sequences,
                    }
                    for item in relevant
                ],
            },
        )
        states.append(result.mastery_state)

    outcome = (
        "requires_review"
        if attempt.status == "requires_review"
        else "mastered"
        if states
        and all(state == "mastered" for state in states)
        and (attempt.score or 0) >= attempt.grading_policy.pass_threshold
        else "passed"
        if (attempt.score or 0) >= attempt.grading_policy.pass_threshold
        else "failed"
    )
    type(attempt).objects.filter(pk=attempt.pk).update(outcome=outcome)


class Migration(migrations.Migration):
    dependencies = [("lab", "0010_versioned_simulation")]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("requires_review", "Requires review"),
                    ("mastered", "Mastered"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="gradingpolicy",
            name="pass_threshold",
            field=models.PositiveSmallIntegerField(
                default=80,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedure_steps",
                to="lab.competency",
            ),
        ),
        migrations.CreateModel(
            name="Hazard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("mitigation", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazards",
                        to="lab.course",
                    ),
                ),
            ],
            options={"ordering": ["-severity", "title"]},
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="hazards",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedure_steps",
                to="lab.hazard",
            ),
        ),
        migrations.CreateModel(
            name="StepFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("safety", "Safety violation"),
                            ("tolerance", "Outside tolerance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_rules",
                        to="lab.procedurestep",
                    ),
                ),
            ],
            options={"ordering": ["outcome"]},
        ),
        migrations.CreateModel(
            name="StepHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("text", models.TextField()),
                ("points_penalty", models.PositiveSmallIntegerField(default=0)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="lab.procedurestep",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="StepResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_code", models.SlugField(max_length=80)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("requires_review", "Requires review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("attempts_count", models.PositiveIntegerField(default=1)),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("achieved_points", models.DecimalField(decimal_places=2, max_digits=8)),
                ("available_points", models.DecimalField(decimal_places=2, max_digits=8)),
                ("tolerance_passed", models.BooleanField(blank=True, null=True)),
                ("safety_violations", models.PositiveIntegerField(default=0)),
                ("evidence_sequences", models.JSONField(default=list)),
                ("completed_at", models.DateTimeField()),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_results",
                        to="lab.attempt",
                    ),
                ),
            ],
            options={"ordering": ["attempt", "step_code"]},
        ),
        migrations.CreateModel(
            name="StepTolerance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("measurement", models.CharField(max_length=120)),
                ("minimum_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("maximum_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit", models.CharField(max_length=40)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tolerances",
                        to="lab.procedurestep",
                    ),
                ),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="AcceptableAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_code", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=180)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptable_actions",
                        to="lab.procedurestep",
                    ),
                ),
                (
                    "tolerance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptable_actions",
                        to="lab.steptolerance",
                    ),
                ),
            ],
            options={"ordering": ["-is_primary", "action_code"]},
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="lab.course",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="required_tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedure_steps",
                to="lab.tool",
            ),
        ),
        migrations.CreateModel(
            name="CompetencyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competency_code", models.CharField(max_length=60)),
                ("achieved_points", models.DecimalField(decimal_places=2, max_digits=8)),
                ("available_points", models.DecimalField(decimal_places=2, max_digits=8)),
                ("mastery_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "mastery_threshold",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "mastery_state",
                    models.CharField(
                        choices=[
                            ("not_demonstrated", "Not demonstrated"),
                            ("developing", "Developing"),
                            ("mastered", "Mastered"),
                            ("requires_review", "Requires review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("evidence", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competency_results",
                        to="lab.attempt",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="lab.competency",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt", "competency_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "competency"),
                        name="unique_attempt_competency_result",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hazard",
            constraint=models.UniqueConstraint(
                fields=("course", "code"),
                name="unique_course_hazard_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepfeedback",
            constraint=models.UniqueConstraint(
                fields=("step", "outcome"),
                name="unique_step_feedback_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="stephint",
            constraint=models.UniqueConstraint(
                fields=("step", "code"),
                name="unique_step_hint_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="stephint",
            constraint=models.UniqueConstraint(
                fields=("step", "order"),
                name="unique_step_hint_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepresult",
            constraint=models.UniqueConstraint(
                fields=("attempt", "step_code"),
                name="unique_attempt_step_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="steptolerance",
            constraint=models.UniqueConstraint(
                fields=("step", "code"),
                name="unique_step_tolerance_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="steptolerance",
            constraint=models.CheckConstraint(
                condition=models.Q(maximum_value__gte=models.F("minimum_value")),
                name="step_tolerance_max_gte_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptableaction",
            constraint=models.UniqueConstraint(
                fields=("step", "action_code"),
                name="unique_step_acceptable_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptableaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_primary=True),
                fields=("step",),
                name="unique_primary_action_per_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="tool",
            constraint=models.UniqueConstraint(
                fields=("course", "code"),
                name="unique_course_tool_code",
            ),
        ),
        migrations.RunPython(
            normalize_steps_and_backfill_results,
            migrations.RunPython.noop,
        ),
    ]
