# Generated by Django 5.2.16 on 2026-08-22 08:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_event_ids(apps, schema_editor):
    AttemptEvent = apps.get_model("lab", "AttemptEvent")
    for event in AttemptEvent.objects.filter(event_id__isnull=True).iterator():
        event.event_id = uuid.uuid4()
        event.save(update_fields=["event_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_assessment_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attempt_limit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='capability_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='renderer_mode',
            field=models.CharField(choices=[('accessible_2d', 'Accessible 2D'), ('desktop_3d', 'Desktop 3D'), ('marker_ar', 'Marker AR'), ('markerless_ar', 'Markerless AR')], default='desktop_3d', max_length=24),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='activity_id',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='client_occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='event_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_event_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attemptevent',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='renderer_mode',
            field=models.CharField(choices=[('accessible_2d', 'Accessible 2D'), ('desktop_3d', 'Desktop 3D'), ('marker_ar', 'Marker AR'), ('markerless_ar', 'Markerless AR')], default='desktop_3d', max_length=24),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AdaptiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.CharField(default='transparent-rules-v1', max_length=80)),
                ('kind', models.CharField(choices=[('continue', 'Continue'), ('remediate', 'Remediate'), ('retry', 'Retry'), ('instructor_review', 'Instructor review'), ('complete', 'Complete')], max_length=32)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('rationale', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='lab.attempt')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaptive_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True)),
                ('feedback', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='lab.attempt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_feedback_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCheckSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_checks', to='lab.assignment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_check_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'learner'), name='unique_assignment_learner_knowledge_check')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=80)),
                ('instrument', models.CharField(choices=[('tam', 'Technology Acceptance Model'), ('sus', 'System Usability Scale'), ('pre_test', 'Pre-test'), ('post_test', 'Post-test'), ('transfer', 'Practical transfer'), ('interview', 'Interview')], max_length=24)),
                ('responses', models.JSONField(default=dict)),
                ('consent_version', models.CharField(max_length=80)),
                ('scenario_version', models.CharField(blank=True, max_length=80)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='lab.school')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'participant_code', 'instrument', 'scenario_version'), name='unique_participant_instrument_scenario')],
            },
        ),
    ]
