# Generated by Django 5.2.16 on 2026-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_assignment_attempt_limit_assignment_available_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='override_kind',
            field=models.CharField(blank=True, choices=[('continue', 'Continue'), ('remediate', 'Remediate'), ('retry', 'Retry'), ('instructor_review', 'Instructor review'), ('complete', 'Complete')], max_length=32, null=True),
        ),
    ]
