# Generated by Django 5.2.16 on 2026-08-22 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_attempt_abandoned_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchConsentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=80)),
                ('consent_version', models.CharField(max_length=80)),
                ('scenario_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='active', max_length=16)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_receipts', to='lab.school')),
            ],
            options={
                'ordering': ['-consented_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'participant_code', 'consent_version', 'scenario_version'), name='unique_research_consent_receipt')],
            },
        ),
    ]
