# Generated by Django 5.2.16 on 2026-08-22 13:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_researchconsentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('protocol_version', models.CharField(max_length=80)),
                ('consent_version', models.CharField(max_length=80)),
                ('instruments', models.JSONField(default=dict)),
                ('supported_devices', models.JSONField(default=list)),
                ('analysis_plan', models.JSONField(default=dict)),
                ('thresholds', models.JSONField(default=dict)),
                ('protocol_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('frozen', 'Protocol frozen'), ('collecting', 'Collecting evidence'), ('closed', 'Collection closed'), ('reviewed', 'Independently reviewed')], default='draft', max_length=16)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('collection_started_at', models.DateTimeField(blank=True, null=True)),
                ('collection_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_studies', to='lab.cohort')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_studies_created', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilot_studies_frozen', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_studies', to='lab.simulationscenario')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_studies', to='lab.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('expand', 'Approve expansion'), ('limit', 'Continue with limits'), ('reject', 'Reject expansion')], max_length=16)),
                ('reviewer_name', models.CharField(max_length=180)),
                ('reviewer_role', models.CharField(max_length=180)),
                ('organization', models.CharField(max_length=180)),
                ('evidence_reference', models.CharField(max_length=500)),
                ('rationale', models.TextField()),
                ('limitations', models.TextField()),
                ('independent_confirmed', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_reviews_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='lab.pilotstudy')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotRehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('instructor_training', 'Instructor training'), ('custodian_training', 'Device-custodian training'), ('outage', 'Outage and synchronization'), ('fallback', 'Fallback and accessibility'), ('stop', 'Safety stop'), ('usability_safety', 'Small usability and safety rehearsal')], max_length=32)),
                ('outcome', models.CharField(choices=[('pass', 'Passed'), ('issues', 'Issues found'), ('fail', 'Failed')], max_length=16)),
                ('facilitator', models.CharField(max_length=180)),
                ('participant_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('evidence_reference', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_rehearsals_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rehearsals', to='lab.pilotstudy')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='PilotObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=80)),
                ('instrument', models.CharField(choices=[('pre_test', 'Pre-test'), ('post_test', 'Post-test'), ('transfer', 'Independent transfer rubric'), ('sus', 'System Usability Scale'), ('tam', 'Technology Acceptance Model'), ('learner_interview', 'Learner interview codes'), ('instructor_interview', 'Instructor interview codes'), ('instructor_workload', 'Instructor workload')], max_length=32)),
                ('responses', models.JSONField(default=dict)),
                ('consent_version', models.CharField(max_length=80)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_observations_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='lab.pilotstudy')),
            ],
            options={
                'ordering': ['instrument', 'participant_code'],
            },
        ),
        migrations.CreateModel(
            name='PilotIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('safety', 'Safety'), ('usability', 'Usability'), ('privacy', 'Privacy'), ('technical', 'Technical'), ('support', 'Support')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('accepted_risk', 'Accepted risk')], default='open', max_length=20)),
                ('summary', models.CharField(max_length=500)),
                ('resolution', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=500)),
                ('safety_critical', models.BooleanField(default=False)),
                ('ar_caused_grading_penalty', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='lab.pilotstudy')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('ethics', 'Ethics'), ('privacy', 'Privacy'), ('safeguarding', 'Safeguarding'), ('instructor', 'Qualified instructor'), ('safety', 'Workshop safety'), ('device', 'Device baseline'), ('accessibility', 'Accessibility'), ('security', 'Security'), ('operations', 'School operations'), ('recovery', 'Recovery'), ('evidence', 'Research evidence')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approver_name', models.CharField(blank=True, max_length=180)),
                ('approver_role', models.CharField(blank=True, max_length=180)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('evidence_reference', models.CharField(blank=True, max_length=500)),
                ('scope', models.TextField(blank=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_approvals_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lab.pilotstudy')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.AddConstraint(
            model_name='pilotstudy',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_pilot_code'),
        ),
        migrations.AddConstraint(
            model_name='pilotrehearsal',
            constraint=models.UniqueConstraint(fields=('study', 'kind'), name='unique_pilot_rehearsal_kind'),
        ),
        migrations.AddConstraint(
            model_name='pilotobservation',
            constraint=models.UniqueConstraint(fields=('study', 'participant_code', 'instrument'), name='unique_pilot_participant_instrument'),
        ),
        migrations.AddConstraint(
            model_name='pilotapproval',
            constraint=models.UniqueConstraint(fields=('study', 'domain'), name='unique_pilot_approval_domain'),
        ),
    ]
