# Generated by Django 5.2.16 on 2026-08-22 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_pilotstudy_pilotreview_pilotrehearsal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_event_ids', models.JSONField(default=list)),
                ('server_event_ids', models.JSONField(default=list)),
                ('missing_event_ids', models.JSONField(default=list)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('client_created_at', models.DateTimeField()),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_audits', to='lab.attempt')),
            ],
            options={
                'ordering': ['-audited_at'],
            },
        ),
    ]
