# Generated by Django 5.2.16 on 2026-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_attemptsyncaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilotrehearsal',
            options={'ordering': ['kind', 'completed_at', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='pilotrehearsal',
            name='unique_pilot_rehearsal_kind',
        ),
        migrations.AlterField(
            model_name='attemptsyncaudit',
            name='client_event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attemptsyncaudit',
            name='missing_event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attemptsyncaudit',
            name='server_event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
